### ISSUE TITLE
Excreta breaks tracks

### ISSUE THREAD

**Issue by PitchBright** [a3626a/HungryAnimals-2.1-1.8.9#1]
Would it be possible to make it so that if an animal poops on a track, the Excreta breaks and disappears, instead of the Tracks being replaced by Excreta?

**Comment by a3626a** [comment]
That's possible.

but I supposed that excreta is some kind of liquid, in solid form. so I made excreta break blocks that are breakable by water.

However, if I disable this function, excreta will still on tall grass. This is quite weird.
(http://i.imgur.com/l1qeRLN.png)

To accept your suggestion and to fix this bug, I have to work more.

In conclusion, Okay I will fix it.

**Comment by a3626a** [comment]
Tracks(Material.circuit) are not replacable by excreta including falling blocks and newly created blocks by animals.
